export const UPDATE_COUNTRIES_LIST = 'UPDATE_COUNTRIES_LIST';
export const ADD_SELECTED_COUNTRY = 'ADD_SELECTED_COUNTRY';
export const DELETE_SELECTED_COUNTRY = 'DELETE_SELECTED_COUNTRY';
export const INIT_FROM_RANGE = 'INIT_FROM_RANGE';
export const INIT_TO_RANGE = 'INIT_TO_RANGE';
export const CHANGE_YEAR_FROM = 'CHANGE_YEAR_FROM';
export const CHANGE_YEAR_TO = 'CHANGE_YEAR_TO';
